services:
  db:
    image: postgres:17
    container_name: cdc_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdc_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres","-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]

